# CI file for GitLab

# Set defaults for variables
variables:
   PITCH_BOOSTER_VERSION: "skeleton"
   PITCH_BOOSTER_IMAGE: $CI_REGISTRY_IMAGE:${PITCH_BOOSTER_VERSION}
   MAC_ADDRESS: ""
   LICENSE: ""

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - build
  - inject

# Build the Booster image
buildjob:
  stage: build
  script:
    - docker build -t $PITCH_BOOSTER_IMAGE --build-arg PITCH_BOOSTER_VERSION=$PITCH_BOOSTER_VERSION docker/context
    - docker push $PITCH_BOOSTER_IMAGE
    
# Inject license key, but only if a key and MAC address are provided
injectjob:
  stage: inject
  script:
    - docker run --mac-address=${MAC_ADDRESS} --name booster ${PITCH_BOOSTER_IMAGE} -l ${LICENSE}
    - docker commit -c 'ENTRYPOINT ["/bin/sh", "./start.sh"]' booster ${PITCH_BOOSTER_IMAGE}L
    - docker rm booster
    - docker push ${PITCH_BOOSTER_IMAGE}L
  only:
    variables:
      - $LICENSE != "" && $MAC_ADDRESS != ""
